version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "proxy"
    depends_on:
      - "proxy"
    networks:
      - "default"
      - "proxy-tier"

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    depends_on:
      - proxy-letsencrypt
      - proxy
    environment:
      - VIRTUAL_HOST=docker.rgsc.top
      - LETSENCRYPT_HOST=docker.rgsc.top
      - LETSENCRYPT_EMAIL=yi-qun.xu@foxmail.com
      - VIRTUAL_PORT=9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9000:9000"


  db-nextcloud:
     image: mariadb:latest
     container_name: db-nextcloud
     networks:
       - "proxy-tier"
     volumes:
      - db-nextcloud:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
     environment:
       - MYSQL_ROOT_PASSWORD=Cka4tQKzHvk6Kxc9Qz69
       - MYSQL_PASSWORD=2g8kRiooy9GKnETgh23R
       - MYSQL_DATABASE=nextcloud
       - MYSQL_USER=nextcloud
     restart: unless-stopped
  
  nextcloud:
     image: nextcloud:latest
     container_name: nextcloud
     networks:
       - "proxy-tier"
     depends_on:
       - proxy-letsencrypt
       - proxy
       - db-nextcloud
     volumes:
       - nextcloud:/var/www/html
       - /etc/localtime:/etc/localtime:ro
     environment:
       - VIRTUAL_HOST=pan.rgsc.top
       - LETSENCRYPT_HOST=pan.rgsc.tk
       - LETSENCRYPT_EMAIL=yi-qun.xu@foxmail.com
     restart: unless-stopped


  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - VIRTUAL_HOST=git.rgsc.top
      - LETSENCRYPT_HOST=git.rgsc.top
      - LETSENCRYPT_EMAIL=yi-qun.xu@foxmail.com
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://git.rgsc.top
      - DOMAIN=git.rgsc.top
      - PROTOCOL=http
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    networks:
      - "proxy-tier"
      - "default"
    depends_on:
      - proxy-letsencrypt
      - proxy
    volumes:
      - gitea:/data
    ports:
      - "9002:3000"
      - "222:22"

  db-ghost:
    image: mariadb:latest
    container_name: db-ghost
    networks:
      - "proxy-tier"
    volumes:
      - db-ghost:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=Cka4tQKzHvk6Kxc9Qz69
      - MYSQL_PASSWORD=2g8kRiooy9GKnETgh23R
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
    restart: unless-stopped


  ghost:
    image: ghost:3
    container_name: ghost
    restart: always
    networks:
      - "proxy-tier"
    volumes:
      - ghost:/var/lib/ghost/content
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - proxy-letsencrypt
      - proxy
      - db-ghost
    ports:
      - 9004:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      - NODE_ENV=production
      - url=https://www.rgsc.top
      - database__client=mysql
      - database__connection__host=db-ghost
      - database__connection__user=ghost
      - database__connection__password=2g8kRiooy9GKnETgh23R
      - database__connection__database=ghost
      - VIRTUAL_HOST=www.rgsc.top
      - LETSENCRYPT_HOST=www.rgsc.top
      - LETSENCRYPT_EMAIL=yi-qun.xu@foxmail.com
      - VIRTUAL_PORT=2368

  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - jupyterhub:/srv/jupyterhub
    environment:
      - VIRTUAL_HOST=jupyter.rgsc.top
      - LETSENCRYPT_HOST=jupyter.rgsc.top
      - LETSENCRYPT_EMAIL=yi-qun.xu@foxmail.com
      - VIRTUAL_PORT=8000
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HUB_IP=jupyterhub
    networks:
      - "proxy-tier"
      - "default"
    depends_on:
      - proxy-letsencrypt
      - proxy
    restart:
      on-failure
    ports:
      - "9003:8000"

  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo


volumes:
  certs:
  vhost.d:
  html:
  portainer:
  gitea:
  db-ghost:
  ghost:
  db-nextcloud:
  nextcloud:
  jupyterhub:


networks:
  proxy-tier:
